name: Run Lighthouse and Store Results for Multiple Pages

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:      # Allows manual execution

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensures repo files are available

      - name: Install Lighthouse CLI
        run: npm install -g lighthouse

      - name: Install jq (JSON Parser)
        run: sudo apt-get install -y jq

      - name: Install Chromium (if required)
        run: sudo apt-get install -y chromium-browser

      - name: Loop Through URLs from Secret
        run: |
          # Fetch URLs from GitHub Secrets
          TARGET_URLS="${{ secrets.TARGET_URL }}"
          
          # Split URLs into an array
          IFS=',' read -r -a URL_ARRAY <<< "$TARGET_URL"
          
          # Loop through each URL
          for url in "${URL_ARRAY[@]}"; do
            echo "Running Lighthouse for $url"

            # Create a temporary directory for reports
            TEMP_DIR=$(mktemp -d)
            echo "Temporary directory created: $TEMP_DIR"

            # Run Lighthouse for JSON output
            lighthouse "$url" --output=json --quiet --chrome-flags="--no-sandbox --headless --disable-dev-shm-usage" \
              --output-path="$TEMP_DIR/report.json"

            # Run Lighthouse for HTML output
            lighthouse "$url" --output=html --quiet --chrome-flags="--no-sandbox --headless --disable-dev-shm-usage" \
              --output-path="$TEMP_DIR/report.html"

            # Check if the JSON report exists
            if [ ! -f "$TEMP_DIR/report.json" ]; then
              echo "Error: Lighthouse did not generate report.json for $url. Skipping..."
              rm -rf "$TEMP_DIR"
              continue
            fi

            # Extract scores using jq
            PERFORMANCE=$(jq -r '.categories.performance.score * 100' "$TEMP_DIR/report.json")
            ACCESSIBILITY=$(jq -r '.categories.accessibility.score * 100' "$TEMP_DIR/report.json")
            BEST_PRACTICES=$(jq -r '.categories."best-practices".score * 100' "$TEMP_DIR/report.json")
            SEO=$(jq -r '.categories.seo.score * 100' "$TEMP_DIR/report.json")

            # Log results for debugging
            echo "Performance: $PERFORMANCE, Accessibility: $ACCESSIBILITY, Best Practices: $BEST_PRACTICES, SEO: $SEO"

            # Insert scores into the database
            echo "INSERT INTO lighthouse_tests (url, performance_score, accessibility_score, best_practices_score, seo_score, timestamp)
            VALUES ('$url', $PERFORMANCE, $ACCESSIBILITY, $BEST_PRACTICES, $SEO, NOW());" | psql "${{ secrets.DATABASE_URL }}"

            # Rename and move the HTML report
            REPORT_FILENAME="lighthouse_$(echo $url | sed 's/[^a-zA-Z0-9]/_/g').html"
            mv "$TEMP_DIR/report.html" "$REPORT_FILENAME"

            # Clean up temporary directory
            rm -rf "$TEMP_DIR"
            echo "Temporary directory cleaned up: $TEMP_DIR"
          done

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install @vercel/blob

      - name: Debug - Verify Files Before Upload
        run: |
          echo "Current directory:"
          pwd
          echo "Listing all files in repo:"
          ls -R
          echo "Checking for Lighthouse reports..."
          ls -al lighthouse_*.html || echo "No reports found!"

      - name: Upload Lighthouse Reports to Vercel Blob
        env:
          VERCEL_BLOB_TOKEN: ${{ secrets.VERCEL_BLOB_TOKEN }}
        run: |
          for report in lighthouse_*.html; do
            if [ -f "$report" ]; then
              echo "Uploading: $report"
              node scripts/uploadToVercelBlob.js "$report"
            else
              echo "Error: Report $report not found!"
            fi
          done
