name: Run Lighthouse and Store Results

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:      # Allows manual execution

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Lighthouse CLI
        run: npm install -g lighthouse

      - name: Install jq (JSON Parser)
        run: sudo apt-get install -y jq

      - name: Run Lighthouse on Target URL
        run: |
          lighthouse ${{ secrets.TARGET_URL }} --output=json --quiet > report.json

      - name: Extract Lighthouse Scores
        id: extract_scores
        run: |
          echo "PERFORMANCE=$(jq -r '.categories.performance.score * 100' report.json)" >> $GITHUB_ENV
          echo "ACCESSIBILITY=$(jq -r '.categories.accessibility.score * 100' report.json)" >> $GITHUB_ENV
          echo "BEST_PRACTICES=$(jq -r '.categories.\"best-practices\".score * 100' report.json)" >> $GITHUB_ENV
          echo "SEO=$(jq -r '.categories.seo.score * 100' report.json)" >> $GITHUB_ENV
          echo "URL=${{ secrets.TARGET_URL }}" >> $GITHUB_ENV

      - name: Store Lighthouse Scores in Vercel Postgres (NeonDB)
        run: |
          psql "${{ secrets.DATABASE_URL }}" <<EOF
          INSERT INTO lighthouse_tests (url, performance_score, accessibility_score, best_practices_score, seo_score, timestamp)
          VALUES ('$URL', $PERFORMANCE, $ACCESSIBILITY, $BEST_PRACTICES, $SEO, NOW());
          EOF
