name: Run Lighthouse and Store Results for Multiple Pages

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:      # Allows manual execution

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Install Lighthouse CLI
        run: npm install -g lighthouse

      - name: Install jq (JSON Parser)
        run: sudo apt-get install -y jq

      - name: Loop Through URLs from Secret
        run: |
          # Fetch URLs from GitHub Secrets
          TARGET_URLS="${{ secrets.TARGET_URL }}"
          
          # Split URLs into an array
          IFS=',' read -r -a URL_ARRAY <<< "$TARGET_URLS"
          
          # Loop through each URL
          for url in "${URL_ARRAY[@]}"; do
            echo "Running Lighthouse for $url"
            lighthouse "$url" --output=json --quiet --chrome-flags="--no-sandbox --headless --disable-dev-shm-usage" > report.json

            PERFORMANCE=$(jq -r '.categories.performance.score * 100' report.json)
            ACCESSIBILITY=$(jq -r '.categories.accessibility.score * 100' report.json)
            BEST_PRACTICES=$(jq -r '.categories."best-practices".score * 100' report.json)
            SEO=$(jq -r '.categories.seo.score * 100' report.json)

            # Log Variables for Debugging
            echo "URL: $url"
            echo "Performance: $PERFORMANCE"
            echo "Accessibility: $ACCESSIBILITY"
            echo "Best Practices: $BEST_PRACTICES"
            echo "SEO: $SEO"

            # Store Results in Database
            echo "INSERT INTO lighthouse_tests (url, performance_score, accessibility_score, best_practices_score, seo_score, timestamp)
            VALUES ('$url', $PERFORMANCE, $ACCESSIBILITY, $BEST_PRACTICES, $SEO, NOW());" | psql "${{ secrets.DATABASE_URL }}"
          done
